# ----------------------- #
#   SITE CONFIGURATION    #
# ----------------------- #

# Basic settings for your site
title: Francisco Banegas
email: fbanegas85@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Cogito, ergo sudo. .
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: jekyll-theme-chirpy # <-- Theme change here
permalink: /:title/ # <-- Your desired permalink structure
timezone: America/Argentina/Buenos_Aires # IMPORTANT: Set your timezone
lang: es # Language code, es for Spanish

# Chirpy's standard settings (Necessary for the theme to work)
# Refer to Chirpy's documentation for detailed options.
tag_page: true
category_page: true
post:
  date_string: "%b %-d, %Y" # Date format for posts
  excerpt_max_length: 200 # Max length for the excerpt

# Author details
author:
  name: Francisco Banegas
  email: fbanegas85@gmail.com
  link: # Add your LinkedIn or personal website URL here

# Social links (Chirpy supports many, ensure usernames are correct)
github_username: FranciscoBanegas
youtube_username: Franciscobanegas

# Header pages—Chirpy layout
# Chirpy uses this to define which pages appear in the main navigation.
header_pages:
  - about.md
  # Add other pages like 'archives.html', 'categories.html', 'tags.html' if you create them.

# ----------------------- #
#   ADVANCED SETTINGS     #
# ----------------------- #

# Build settings (Default Jekyll settings, keep them clean)
markdown: kramdown
highlighter: rouge

# Exclude from processing.
# The following items will not be processed, by default.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - LICENSE
  - README.md
  - CNAME
